export const GET_UPCOMING_DEBATES = 'GET_UPCOMING_DEBATES';
export const GET_UPCOMING_DEBATES_SUCCESS = 'GET_UPCOMING_DEBATES_SUCCESS';
export const GET_UPCOMING_DEBATES_FAIL = 'GET_UPCOMING_DEBATES_FAIL';

export const VOTE_UPCOMING_DEBATE = 'VOTE_UPCOMING_DEBATE';
export const VOTE_UPCOMING_DEBATE_SUCCESS = 'VOTE_UPCOMING_DEBATE_SUCCESS';
export const VOTE_UPCOMING_DEBATE_FAIL = 'VOTE_UPCOMING_DEBATE_FAIL';
