export const POST_UPVOTE         = 'POST_UPVOTE';
export const POST_UPVOTE_SUCCESS = 'POST_UPVOTE_SUCCESS';
export const POST_UPVOTE_FAIL    = 'POST_UPVOTE_FAIL';
export const POST_UNVOTE         = 'POST_UNVOTE';
export const POST_UNVOTE_SUCCESS = 'POST_UNVOTE_SUCCESS';
export const POST_UNVOTE_FAIL    = 'POST_UNVOTE_FAIL';

export const SOCKET_POST_UPVOTE  = 'SOCKET_POST_UPVOTE';
export const SOCKET_POST_UNVOTE  = 'SOCKET_POST_UNVOTE';